global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'js-fastapi-monitoring_web'
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:5000']
